
apiVersion: v1
kind: Service
metadata:
  name: express
spec:
  selector:
    app: {{ lower .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort | default 8080 }}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-cloudflare
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: express.zinkithink.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express
            port:
              number: 80
