name: Build and Push Images to GHCR

on:
  push:
    tags:
      - "*"


jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: 'Get tags'
        run: |
          echo "Tag name: ${{ github.ref_name}}" 
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.PAC}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{  github.ref_name }}
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository }}:${{  github.ref_name }}
          build-args: |
            git_sha=${{ github.sha }}
  bump:
    name: Bump Helm Version
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Update Helm chart
        uses: mikefarah/yq@v4.45.4
        with:
          cmd: |
            yq -i '.version = "${{ github.ref_name }}"' ./helm/Chart.yaml
            yq -i '.appVersion = "${{ github.ref_name }}"' ./helm/Chart.yaml

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.PAC}}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Package and push helm chart
        run: |
          helm package ./helm --version ${{ github.ref_name }}
          helm push ./${{ github.event.repository.name }}-${{ github.ref_name }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts