name: Build and Push Images to GHCR
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'sometimes-forevercd[bot]' }}
    outputs:
      new_version: ${{ steps.tag.outputs.new_release_version }}
    steps:

      - uses: actions/checkout@v4
      
      - name: Get Tag
        uses: cycjimmy/semantic-release-action@v4
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_TOKEN }}
        with:
          dry_run: true

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.FULL_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{  steps.tag.outputs.new_release_version }}
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository }}:${{  steps.tag.outputs.new_release_version }}
          build-args: |
            git_sha=${{ github.sha }}

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  bump:
    name: Bump Helm Version
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Update Helm chart
        uses: mikefarah/yq@v4.45.4
        with:
          cmd: |
            yq -i '.version = "${{ needs.build.outputs.new_version }}"' ./helm/Chart.yaml
            yq -i '.appVersion = "${{ needs.build.outputs.new_version }}"' ./helm/Chart.yaml

      - name: Commit changes
        run: |
          git config --local user.email "${{ vars.APP_ID }}+sometimes-forevercd[bot]@users.noreply.github.com"
          git config --local user.name "sometimes-forevercd[bot]"
          git commit -am "Bump verison to ${{ needs.build.outputs.new_version }} [no ci]"

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.FULL_TOKEN}}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Package and push helm chart
        run: |
          helm package ./helm --version ${{ needs.build.outputs.new_version }}
          helm push ./${{ github.event.repository.name }}-${{ needs.build.outputs.new_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts